/* file: comparison_less.swift 	 generated: Wed Jan 21 18:03:37 2026 */

/* This file was generated by the EXPRESS to Swift translator "exp2swift", 
    derived from STEPcode (formerly NIST's SCL).
 exp2swift version: v.2.0.0, derived from stepcode v0.8 as of 2019/11/23 
 WARNING: You probably don't want to edit it since your modifications 
    will be lost if exp2swift is used to regenerate it.
 */

 
import SwiftSDAIcore

extension AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF {
//MARK: -ENTITY DEFINITION in EXPRESS
/*

  ENTITY comparison_less
    SUBTYPE OF ( comparison_expression );
  END_ENTITY; -- comparison_less (line:9775 file:ap242ed2_mim_lf_v1.101_TY.exp)

*/


//MARK: - ALL DEFINED ATTRIBUTES
/*
  SUPER- ENTITY(1)	generic_expression
    (no local attributes)

  SUPER- ENTITY(2)	expression
    (no local attributes)

  SUPER- ENTITY(3)	boolean_expression
    (no local attributes)

  SUPER- ENTITY(4)	binary_generic_expression
    ATTR:  operands,	TYPE: LIST [2 : 2] OF generic_expression -- EXPLICIT
      -- possibly overridden by
          ENTITY: binary_numeric_expression,	TYPE: LIST [2 : 2] OF numeric_expression
          ENTITY: xor_expression,	TYPE: LIST [2 : 2] OF boolean_expression
      *** ENTITY: comparison_expression,	TYPE: LIST [2 : 2] OF expression


  SUPER- ENTITY(5)	comparison_expression
    REDCR: operands,	TYPE: LIST [2 : 2] OF expression -- EXPLICIT
      -- OVERRIDING ENTITY: binary_generic_expression


  ENTITY(SELF)	comparison_less
    (no local attributes)

*/


//MARK: - Entity Reference

/** ENTITY reference
- EXPRESS source code:
```express
  ENTITY comparison_less
    SUBTYPE OF ( comparison_expression );
  END_ENTITY; -- comparison_less (line:9775 file:ap242ed2_mim_lf_v1.101_TY.exp)

```

- SUPERTYPES:
	1.	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eGENERIC_EXPRESSION``
	2.	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eEXPRESSION``
	3.	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eBOOLEAN_EXPRESSION``
	4.	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eBINARY_GENERIC_EXPRESSION``
	5.	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eCOMPARISON_EXPRESSION``

- SUBTYPES:

- PARTIAL ENTITY:
	+	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eCOMPARISON_LESS/PartialEntity``
*/
  public final class eCOMPARISON_LESS : SDAI.EntityReference, SDAI.DualModeReference, @unchecked Sendable {
    /// persistent entity reference type
    public typealias PRef = SDAI.PersistentEntityReference<eCOMPARISON_LESS>

    /// persistent entity reference
    public var pRef: PRef { PRef(self) }


    //MARK: PARTIAL ENTITY
    public override class var partialEntityType: SDAI.PartialEntity.Type {
      eCOMPARISON_LESS.PartialEntity.self
    }
    /// partial entity reference
    public let partialEntity: eCOMPARISON_LESS.PartialEntity

    //MARK: SUPERTYPES
    public let super_eGENERIC_EXPRESSION: eGENERIC_EXPRESSION 	// [1]
    public let super_eEXPRESSION: eEXPRESSION 	// [2]
    public let super_eBOOLEAN_EXPRESSION: eBOOLEAN_EXPRESSION 	// [3]
    public let super_eBINARY_GENERIC_EXPRESSION: eBINARY_GENERIC_EXPRESSION 	// [4]
    public let super_eCOMPARISON_EXPRESSION: eCOMPARISON_EXPRESSION 	// [5]
    public var super_eCOMPARISON_LESS: eCOMPARISON_LESS { return self } 	// [6]

    //MARK: SUBTYPES

    //MARK: ATTRIBUTES
    /// __EXPLICIT REDEF__ attribute
    /// - origin: SUPER( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eCOMPARISON_EXPRESSION`` )
    public var OPERANDS: SDAI.LIST<eEXPRESSION.PRef>/*[2:2]*/  {
      get {
        return SDAI.UNWRAP( SDAI.LIST<eEXPRESSION.PRef>( super_eBINARY_GENERIC_EXPRESSION.partialEntity
          ._operands ) )
      }
      set(newValue) {
        let partial = super_eBINARY_GENERIC_EXPRESSION.partialEntity
        partial._operands = SDAI.UNWRAP(
          SDAI.LIST<eGENERIC_EXPRESSION.PRef>(fromGeneric: newValue))
      }
    }


    //MARK: INITIALIZERS
    /// initialize from entity reference (type conversion form)
    public convenience init?(_ entityRef: SDAI.EntityReference?) {
      let complex = entityRef?.complexEntity
      self.init(complex: complex)
    }

    /// initialize from complex entity
    public required init?(complex complexEntity: SDAI.ComplexEntity?) {
      guard let partial = complexEntity?.partialEntityInstance(eCOMPARISON_LESS.PartialEntity.self) else { return nil }
      self.partialEntity = partial

      guard let super1 = complexEntity?.entityReference(eGENERIC_EXPRESSION.self) else { return nil }
      self.super_eGENERIC_EXPRESSION = super1

      guard let super2 = complexEntity?.entityReference(eEXPRESSION.self) else { return nil }
      self.super_eEXPRESSION = super2

      guard let super3 = complexEntity?.entityReference(eBOOLEAN_EXPRESSION.self) else { return nil }
      self.super_eBOOLEAN_EXPRESSION = super3

      guard let super4 = complexEntity?.entityReference(eBINARY_GENERIC_EXPRESSION.self) else { return nil }
      self.super_eBINARY_GENERIC_EXPRESSION = super4

      guard let super5 = complexEntity?.entityReference(eCOMPARISON_EXPRESSION.self) else { return nil }
      self.super_eCOMPARISON_EXPRESSION = super5

      super.init(complex: complexEntity)
    }

    /// initialize from SDAI generic type
    public required convenience init?<G: SDAI.GenericType>(fromGeneric generic: G?) {
      guard let entityRef = generic?.entityReference else { return nil }
      self.init(complex: entityRef.complexEntity)
    }

    /// initialize from SDAI select type (type conversion form)
    public convenience init?<S: SDAI.SelectType>(_ select: S?) { self.init(possiblyFrom: select) }
    /// initialize from complex entity (type conversion form)
    public convenience init?(_ complex: SDAI.ComplexEntity?) { self.init(complex: complex) }


    //MARK: DICTIONARY DEFINITION
    public class override var entityDefinition: SDAIDictionarySchema.EntityDefinition { _entityDefinition }
    private static let _entityDefinition: SDAIDictionarySchema.EntityDefinition = createEntityDefinition()

    private static func createEntityDefinition() -> SDAIDictionarySchema.EntityDefinition {
      let entityDef = SDAIDictionarySchema.EntityDefinition.Prototype( 
        name: "COMPARISON_LESS", 
        type: self, explicitAttributeCount: 0)

      //MARK: SUPERTYPE REGISTRATIONS
      entityDef.add(supertype: eGENERIC_EXPRESSION.self)
      entityDef.add(supertype: eEXPRESSION.self)
      entityDef.add(supertype: eBOOLEAN_EXPRESSION.self)
      entityDef.add(supertype: eBINARY_GENERIC_EXPRESSION.self)
      entityDef.add(supertype: eCOMPARISON_EXPRESSION.self)
      entityDef.add(supertype: eCOMPARISON_LESS.self)

      //MARK: ATTRIBUTE REGISTRATIONS
      entityDef.addAttribute(name: "OPERANDS", 
        keyPath: \eCOMPARISON_LESS.OPERANDS, 
        kind: .explicitRedeclaring, source: .superEntity, mayYieldEntityReference: true)

      return entityDef.freeze()
    }



//MARK: - Partial Entity

/** Partial Entity
- EXPRESS source code:
```express

    ENTITY comparison_less
      SUBTYPE OF ( comparison_expression );
    END_ENTITY; -- comparison_less (line:9775 file:ap242ed2_mim_lf_v1.101_TY.exp)

```
- ENTITY reference:
	+	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eCOMPARISON_LESS``
*/
    public final class PartialEntity : SDAI.PartialEntity, SDAI.Initializable.ByVoid, @unchecked Sendable {
      public override class var entityReferenceType: SDAI.EntityReference.Type {
        eCOMPARISON_LESS.self
      }

      //ATTRIBUTES
      // (no local attributes)

      public override var typeMembers: Set<SDAI.STRING> {
        var members = Set<SDAI.STRING>()
        members.insert(SDAI.STRING(Self.typeName))
        return members
      }


      //VALUE COMPARISON SUPPORT
      public override func hashAsValue(into hasher: inout Hasher, visited complexEntities: inout Set<SDAI.ComplexEntity>) {
        super.hashAsValue(into: &hasher, visited: &complexEntities)
      }

      public override func isValueEqual(to rhs: SDAI.PartialEntity, visited comppairs: inout Set<SDAI.ComplexPair>) -> Bool {
        guard let rhs = rhs as? Self else { return false }
        if !super.isValueEqual(to: rhs, visited: &comppairs) { return false }
        return true
      }

      public override func isValueEqualOptionally(to rhs: SDAI.PartialEntity, visited comppairs: inout Set<SDAI.ComplexPair>) -> Bool? {
        guard let rhs = rhs as? Self else { return false }
        var result: Bool? = true
        if let comp = super.isValueEqualOptionally(to: rhs, visited: &comppairs) {
          if !comp { return false }
        }
        else { result = nil }
        return result
      }


      //EXPRESS IMPLICIT PARTIAL ENTITY CONSTRUCTOR
      /// initialize from explicit attribute values
      public init() {
        super.init(asAbstractSuperclass:())
      }

      //PARTIAL ENTITY COPY CONSTRUCTOR
      /// copy constructor
      public required convenience init(from original:SDAI.PartialEntity) {
        self.init( )
      }

      //p21 PARTIAL ENTITY CONSTRUCTOR
      /// initialize from ISO 10303-21 exchange structure parameters
      public required convenience init?(
        parameters: [P21Decode.ExchangeStructure.Parameter],
        exchangeStructure: P21Decode.ExchangeStructure
      ) {
        let numParams = 0
        guard parameters.count == numParams
        else { exchangeStructure.error = "number of p21 parameters(\(parameters.count)) are different from expected(\(numParams)) for partial entity(\(Self.entityName)) constructor"; return nil }

        self.init( )
      }
    }
  }
}
