/* file: surface_style_rendering.swift 	 generated: Sat Aug 14 13:46:02 2021 */

/* This file was generated by the EXPRESS to Swift translator "exp2swift", 
    derived from STEPcode (formerly NIST's SCL).
 exp2swift version: v.1.0.0, derived from stepcode v0.8 as of 2019/11/23 
 WARNING: You probably don't want to edit it since your modifications 
    will be lost if exp2swift is used to regenerate it.
 */

 
import SwiftSDAIcore

extension AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF {
//MARK: -ENTITY DEFINITION in EXPRESS
/*

  ENTITY surface_style_rendering;
      rendering_method  : shading_surface_method;
      surface_colour    : colour;
  END_ENTITY; -- surface_style_rendering (line:31296 file:ap242ed2_mim_lf_v1.101.TY.exp)

*/


//MARK: - ALL DEFINED ATTRIBUTES
/*
  ENTITY(SELF)	surface_style_rendering
    ATTR:  rendering_method,	TYPE: shading_surface_method -- EXPLICIT

    ATTR:  surface_colour,	TYPE: colour -- EXPLICIT


  SUB- ENTITY(2)	surface_style_rendering_with_properties
    ATTR:  properties,	TYPE: SET [1 : 2] OF rendering_properties_select -- EXPLICIT


*/


//MARK: - Partial Entity
  public final class _surface_style_rendering : SDAI.PartialEntity {
    public override class var entityReferenceType: SDAI.EntityReference.Type {
      eSURFACE_STYLE_RENDERING.self
    }

    //ATTRIBUTES
    /// EXPLICIT ATTRIBUTE 
    public internal(set) var _rendering_method: nSHADING_SURFACE_METHOD // PLAIN EXPLICIT ATTRIBUTE

    /// EXPLICIT ATTRIBUTE 
    public internal(set) var _surface_colour: eCOLOUR // PLAIN EXPLICIT ATTRIBUTE

    public override var typeMembers: Set<SDAI.STRING> {
      var members = Set<SDAI.STRING>()
      members.insert(SDAI.STRING(Self.typeName))
      //SELECT data types (indirectly) referencing the current type as a member of the select list
      members.insert(SDAI.STRING(sSURFACE_STYLE_ELEMENT_SELECT.typeName)) // -> Self
      return members
    }


    //VALUE COMPARISON SUPPORT
    public override func hashAsValue(into hasher: inout Hasher, visited complexEntities: inout Set<SDAI.ComplexEntity>) {
      super.hashAsValue(into: &hasher, visited: &complexEntities)
      self._rendering_method.value.hashAsValue(into: &hasher, visited: &complexEntities)
      self._surface_colour.value.hashAsValue(into: &hasher, visited: &complexEntities)
    }

    public override func isValueEqual(to rhs: SDAI.PartialEntity, visited comppairs: inout Set<SDAI.ComplexPair>) -> Bool {
      guard let rhs = rhs as? Self else { return false }
      if !super.isValueEqual(to: rhs, visited: &comppairs) { return false }
      if let comp = self._rendering_method.value.isValueEqualOptionally(to: rhs._rendering_method.value, visited: &comppairs)	{
        if !comp { return false }
      }
      else { return false }
      if let comp = self._surface_colour.value.isValueEqualOptionally(to: rhs._surface_colour.value, visited: &comppairs)	{
        if !comp { return false }
      }
      else { return false }
      return true
    }

    public override func isValueEqualOptionally(to rhs: SDAI.PartialEntity, visited comppairs: inout Set<SDAI.ComplexPair>) -> Bool? {
      guard let rhs = rhs as? Self else { return false }
      var result: Bool? = true
      if let comp = super.isValueEqualOptionally(to: rhs, visited: &comppairs) {
        if !comp { return false }
      }
      else { result = nil }
      if let comp = self._rendering_method.value.isValueEqualOptionally(to: rhs._rendering_method.value, visited: &comppairs) {
        if !comp { return false }
      }
      else { result = nil }
      if let comp = self._surface_colour.value.isValueEqualOptionally(to: rhs._surface_colour.value, visited: &comppairs) {
        if !comp { return false }
      }
      else { result = nil }
      return result
    }


    //EXPRESS IMPLICIT PARTIAL ENTITY CONSTRUCTOR
    public init(RENDERING_METHOD: nSHADING_SURFACE_METHOD, SURFACE_COLOUR: eCOLOUR) {
      self._rendering_method = RENDERING_METHOD
      self._surface_colour = SURFACE_COLOUR
      super.init(asAbstructSuperclass:())

    }

    //p21 PARTIAL ENTITY CONSTRUCTOR
    public required convenience init?(parameters: [P21Decode.ExchangeStructure.Parameter], exchangeStructure: P21Decode.ExchangeStructure) {
      let numParams = 2
      guard parameters.count == numParams
      else { exchangeStructure.error = "number of p21 parameters(\(parameters.count)) are different from expected(\(numParams)) for entity(\(Self.entityName)) constructor"; return nil }

      guard case .success(let p0) = exchangeStructure.recoverRequiredParameter(as: nSHADING_SURFACE_METHOD.self, from: parameters[0])
      else { exchangeStructure.add(errorContext: "while recovering parameter #0 for entity(\(Self.entityName)) constructor"); return nil }

      guard case .success(let p1) = exchangeStructure.recoverRequiredParameter(as: eCOLOUR.self, from: parameters[1])
      else { exchangeStructure.add(errorContext: "while recovering parameter #1 for entity(\(Self.entityName)) constructor"); return nil }

      self.init( RENDERING_METHOD: p0, SURFACE_COLOUR: p1 )
    }
  }


//MARK: - Entity Reference

/** ENTITY reference
- EXPRESS:
```express
  ENTITY surface_style_rendering;
      rendering_method  : shading_surface_method;
      surface_colour    : colour;
  END_ENTITY; -- surface_style_rendering (line:31296 file:ap242ed2_mim_lf_v1.101.TY.exp)

```
*/
  public final class eSURFACE_STYLE_RENDERING : SDAI.EntityReference {

    //MARK: PARTIAL ENTITY
    public override class var partialEntityType: SDAI.PartialEntity.Type {
      _surface_style_rendering.self
    }
    public let partialEntity: _surface_style_rendering

    //MARK: SUPERTYPES
    public var super_eSURFACE_STYLE_RENDERING: eSURFACE_STYLE_RENDERING { return self } 	// [1]

    //MARK: SUBTYPES
    public var sub_eSURFACE_STYLE_RENDERING_WITH_PROPERTIES: eSURFACE_STYLE_RENDERING_WITH_PROPERTIES? {	// [2]
      return self.complexEntity.entityReference(eSURFACE_STYLE_RENDERING_WITH_PROPERTIES.self)
    }


    //MARK: ATTRIBUTES
    /// __EXPLICIT__ attribute
    /// - origin: SUB( ``eSURFACE_STYLE_RENDERING_WITH_PROPERTIES`` )
    public var PROPERTIES: (SDAI.SET<sRENDERING_PROPERTIES_SELECT>/*[1:2]*/ )?  {
      get {
        return sub_eSURFACE_STYLE_RENDERING_WITH_PROPERTIES?.partialEntity._properties
      }
      set(newValue) {
        guard let partial = sub_eSURFACE_STYLE_RENDERING_WITH_PROPERTIES?.super_eSURFACE_STYLE_RENDERING_WITH_PROPERTIES
          .partialEntity else { return }
        partial._properties = SDAI.UNWRAP(newValue)
      }
    }

    /// __EXPLICIT__ attribute
    /// - origin: SELF( ``eSURFACE_STYLE_RENDERING`` )
    public var RENDERING_METHOD: nSHADING_SURFACE_METHOD {
      get {
        return SDAI.UNWRAP( self.partialEntity._rendering_method )
      }
      set(newValue) {
        let partial = self.partialEntity
        partial._rendering_method = SDAI.UNWRAP(newValue)
      }
    }

    /// __EXPLICIT__ attribute
    /// - origin: SELF( ``eSURFACE_STYLE_RENDERING`` )
    public var SURFACE_COLOUR: eCOLOUR {
      get {
        return SDAI.UNWRAP( self.partialEntity._surface_colour )
      }
      set(newValue) {
        let partial = self.partialEntity
        partial._surface_colour = SDAI.UNWRAP(newValue)
      }
    }


    //MARK: INITIALIZERS
    public convenience init?(_ entityRef: SDAI.EntityReference?) {
      let complex = entityRef?.complexEntity
      self.init(complex: complex)
    }

    public required init?(complex complexEntity: SDAI.ComplexEntity?) {
      guard let partial = complexEntity?.partialEntityInstance(_surface_style_rendering.self) else { return nil }
      self.partialEntity = partial

      super.init(complex: complexEntity)
    }

    public required convenience init?<G: SDAIGenericType>(fromGeneric generic: G?) {
      guard let entityRef = generic?.entityReference else { return nil }
      self.init(complex: entityRef.complexEntity)
    }

    public convenience init?<S: SDAISelectType>(_ select: S?) { self.init(possiblyFrom: select) }
    public convenience init?(_ complex: SDAI.ComplexEntity?) { self.init(complex: complex) }

    //SIMPLE ENTITY REFERENCE
    public convenience init?(_ partial:_surface_style_rendering) {
      let complex = SDAI.ComplexEntity(entities:[partial])
      self.init(complex: complex)
    }


    //MARK: DICTIONARY DEFINITION
    public class override var entityDefinition: SDAIDictionarySchema.EntityDefinition { _entityDefinition }
    private static let _entityDefinition: SDAIDictionarySchema.EntityDefinition = createEntityDefinition()

    private static func createEntityDefinition() -> SDAIDictionarySchema.EntityDefinition {
      let entityDef = SDAIDictionarySchema.EntityDefinition(name: "SURFACE_STYLE_RENDERING", type: self, explicitAttributeCount: 2)

      //MARK: SUPERTYPE REGISTRATIONS
      entityDef.add(supertype: eSURFACE_STYLE_RENDERING.self)

      //MARK: ATTRIBUTE REGISTRATIONS
      entityDef.addAttribute(name: "PROPERTIES", keyPath: \eSURFACE_STYLE_RENDERING.PROPERTIES, 
        kind: .explicit, source: .subEntity, mayYieldEntityReference: true)
      entityDef.addAttribute(name: "RENDERING_METHOD", keyPath: \eSURFACE_STYLE_RENDERING.RENDERING_METHOD, 
        kind: .explicit, source: .thisEntity, mayYieldEntityReference: false)
      entityDef.addAttribute(name: "SURFACE_COLOUR", keyPath: \eSURFACE_STYLE_RENDERING.SURFACE_COLOUR, 
        kind: .explicit, source: .thisEntity, mayYieldEntityReference: true)

      return entityDef
    }

  }
}
