/* file: surface_of_revolution.swift 	 generated: Wed Jan 21 18:03:37 2026 */

/* This file was generated by the EXPRESS to Swift translator "exp2swift", 
    derived from STEPcode (formerly NIST's SCL).
 exp2swift version: v.2.0.0, derived from stepcode v0.8 as of 2019/11/23 
 WARNING: You probably don't want to edit it since your modifications 
    will be lost if exp2swift is used to regenerate it.
 */

 
import SwiftSDAIcore

extension AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF {
//MARK: -ENTITY DEFINITION in EXPRESS
/*
  ENTITY surface_of_revolution
    SUBTYPE OF ( swept_surface );
      axis_position  : axis1_placement;
    DERIVE
      axis_line  : line := representation_item( '' ) || geometric_representation_item(  ) || curve(  ) || 
                     line( axis_position.location, representation_item( '' ) || 
                     geometric_representation_item(  ) || vector( axis_position.z, 1 ) );
  END_ENTITY; -- surface_of_revolution (line:31375 file:ap242ed2_mim_lf_v1.101_TY.exp)

*/


//MARK: - ALL DEFINED ATTRIBUTES
/*
  SUPER- ENTITY(1)	representation_item
    ATTR:  name,	TYPE: label -- EXPLICIT


  SUPER- ENTITY(2)	geometric_representation_item
    ATTR:  dim,	TYPE: dimension_count -- DERIVED
      := dimension_of( SELF )


  SUPER- ENTITY(3)	surface
    (no local attributes)

  SUPER- ENTITY(4)	swept_surface
    ATTR:  swept_curve,	TYPE: curve -- EXPLICIT


  ENTITY(SELF)	surface_of_revolution
    ATTR:  axis_position,	TYPE: axis1_placement -- EXPLICIT

    ATTR:  axis_line,	TYPE: line -- DERIVED
      := representation_item( '' ) || geometric_representation_item(  ) || curve(  ) || line( axis_position.
        location, representation_item( '' ) || geometric_representation_item(  ) || vector( axis_position.z, 
        1 ) )


*/


//MARK: - Entity Reference

/** ENTITY reference
- EXPRESS source code:
```express
  ENTITY surface_of_revolution
    SUBTYPE OF ( swept_surface );
      axis_position  : axis1_placement;
    DERIVE
      axis_line  : line := representation_item( '' ) || geometric_representation_item(  ) || curve(  ) || 
                     line( axis_position.location, representation_item( '' ) || 
                     geometric_representation_item(  ) || vector( axis_position.z, 1 ) );
  END_ENTITY; -- surface_of_revolution (line:31375 file:ap242ed2_mim_lf_v1.101_TY.exp)

```

- SUPERTYPES:
	1.	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eREPRESENTATION_ITEM``
	2.	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eGEOMETRIC_REPRESENTATION_ITEM``
	3.	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eSURFACE``
	4.	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eSWEPT_SURFACE``

- SUBTYPES:

- PARTIAL ENTITY:
	+	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eSURFACE_OF_REVOLUTION/PartialEntity``
*/
  public final class eSURFACE_OF_REVOLUTION : SDAI.EntityReference, SDAI.DualModeReference, 
    @unchecked Sendable {
    /// persistent entity reference type
    public typealias PRef = SDAI.PersistentEntityReference<eSURFACE_OF_REVOLUTION>

    /// persistent entity reference
    public var pRef: PRef { PRef(self) }


    //MARK: PARTIAL ENTITY
    public override class var partialEntityType: SDAI.PartialEntity.Type {
      eSURFACE_OF_REVOLUTION.PartialEntity.self
    }
    /// partial entity reference
    public let partialEntity: eSURFACE_OF_REVOLUTION.PartialEntity

    //MARK: SUPERTYPES
    public let super_eREPRESENTATION_ITEM: eREPRESENTATION_ITEM 	// [1]
    public let super_eGEOMETRIC_REPRESENTATION_ITEM: eGEOMETRIC_REPRESENTATION_ITEM 	// [2]
    public let super_eSURFACE: eSURFACE 	// [3]
    public let super_eSWEPT_SURFACE: eSWEPT_SURFACE 	// [4]
    public var super_eSURFACE_OF_REVOLUTION: eSURFACE_OF_REVOLUTION { return self } 	// [5]

    //MARK: SUBTYPES

    //MARK: ATTRIBUTES
    /// __EXPLICIT__ attribute
    /// - origin: SUPER( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eSWEPT_SURFACE`` )
    public var SWEPT_CURVE: eCURVE.PRef {
      get {
        return SDAI.UNWRAP( super_eSWEPT_SURFACE.partialEntity._swept_curve )
      }
      set(newValue) {
        let partial = super_eSWEPT_SURFACE.partialEntity
        partial._swept_curve = SDAI.UNWRAP(newValue)
      }
    }

    /// __EXPLICIT__ attribute
    /// - origin: SELF( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eSURFACE_OF_REVOLUTION`` )
    public var AXIS_POSITION: eAXIS1_PLACEMENT.PRef {
      get {
        return SDAI.UNWRAP( self.partialEntity._axis_position )
      }
      set(newValue) {
        let partial = self.partialEntity
        partial._axis_position = SDAI.UNWRAP(newValue)
      }
    }

    /// __DERIVE__ attribute
    /// - origin: SELF( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eSURFACE_OF_REVOLUTION`` )
    public var AXIS_LINE: eLINE.PRef?  {
      get {
        if let cached = cachedValue(derivedAttributeName:"AXIS_LINE") {
          return cached.value as! eLINE.PRef? 
        }
        let origin = self
        let value = origin.partialEntity._axis_line__getter(SELF: origin.pRef)
        updateCache(derivedAttributeName:"AXIS_LINE", value:value)
        return value
      }
    }

    /// __EXPLICIT__ attribute
    /// - origin: SUPER( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eREPRESENTATION_ITEM`` )
    public var NAME: tLABEL {
      get {
        return SDAI.UNWRAP( super_eREPRESENTATION_ITEM.partialEntity._name )
      }
      set(newValue) {
        let partial = super_eREPRESENTATION_ITEM.partialEntity
        partial._name = SDAI.UNWRAP(newValue)
      }
    }

    /// __DERIVE__ attribute
    /// - origin: SUPER( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eGEOMETRIC_REPRESENTATION_ITEM`` )
    public var DIM: tDIMENSION_COUNT?  {
      get {
        if let cached = cachedValue(derivedAttributeName:"DIM") {
          return cached.value as! tDIMENSION_COUNT? 
        }
        let origin = super_eGEOMETRIC_REPRESENTATION_ITEM
        let value = tDIMENSION_COUNT(origin.partialEntity._dim__getter(SELF: origin.pRef))
        updateCache(derivedAttributeName:"DIM", value:value)
        return value
      }
    }


    //MARK: INITIALIZERS
    /// initialize from entity reference (type conversion form)
    public convenience init?(_ entityRef: SDAI.EntityReference?) {
      let complex = entityRef?.complexEntity
      self.init(complex: complex)
    }

    /// initialize from complex entity
    public required init?(complex complexEntity: SDAI.ComplexEntity?) {
      guard let partial = complexEntity?.partialEntityInstance(eSURFACE_OF_REVOLUTION.PartialEntity.self) else { return nil }
      self.partialEntity = partial

      guard let super1 = complexEntity?.entityReference(eREPRESENTATION_ITEM.self) else { return nil }
      self.super_eREPRESENTATION_ITEM = super1

      guard let super2 = complexEntity?.entityReference(eGEOMETRIC_REPRESENTATION_ITEM.self) else { return nil }
      self.super_eGEOMETRIC_REPRESENTATION_ITEM = super2

      guard let super3 = complexEntity?.entityReference(eSURFACE.self) else { return nil }
      self.super_eSURFACE = super3

      guard let super4 = complexEntity?.entityReference(eSWEPT_SURFACE.self) else { return nil }
      self.super_eSWEPT_SURFACE = super4

      super.init(complex: complexEntity)
    }

    /// initialize from SDAI generic type
    public required convenience init?<G: SDAI.GenericType>(fromGeneric generic: G?) {
      guard let entityRef = generic?.entityReference else { return nil }
      self.init(complex: entityRef.complexEntity)
    }

    /// initialize from SDAI select type (type conversion form)
    public convenience init?<S: SDAI.SelectType>(_ select: S?) { self.init(possiblyFrom: select) }
    /// initialize from complex entity (type conversion form)
    public convenience init?(_ complex: SDAI.ComplexEntity?) { self.init(complex: complex) }


    //MARK: DICTIONARY DEFINITION
    public class override var entityDefinition: SDAIDictionarySchema.EntityDefinition { _entityDefinition }
    private static let _entityDefinition: SDAIDictionarySchema.EntityDefinition = createEntityDefinition()

    private static func createEntityDefinition() -> SDAIDictionarySchema.EntityDefinition {
      let entityDef = SDAIDictionarySchema.EntityDefinition.Prototype( 
        name: "SURFACE_OF_REVOLUTION", 
        type: self, explicitAttributeCount: 1)

      //MARK: SUPERTYPE REGISTRATIONS
      entityDef.add(supertype: eREPRESENTATION_ITEM.self)
      entityDef.add(supertype: eGEOMETRIC_REPRESENTATION_ITEM.self)
      entityDef.add(supertype: eSURFACE.self)
      entityDef.add(supertype: eSWEPT_SURFACE.self)
      entityDef.add(supertype: eSURFACE_OF_REVOLUTION.self)

      //MARK: ATTRIBUTE REGISTRATIONS
      entityDef.addAttribute(name: "SWEPT_CURVE", 
        keyPath: \eSURFACE_OF_REVOLUTION.SWEPT_CURVE, 
        kind: .explicit, source: .superEntity, mayYieldEntityReference: true)
      entityDef.addAttribute(name: "AXIS_POSITION", 
        keyPath: \eSURFACE_OF_REVOLUTION.AXIS_POSITION, 
        kind: .explicit, source: .thisEntity, mayYieldEntityReference: true)
      entityDef.addAttribute(name: "AXIS_LINE", 
        keyPath: \eSURFACE_OF_REVOLUTION.AXIS_LINE, 
        kind: .derived, source: .thisEntity, mayYieldEntityReference: true)
      entityDef.addAttribute(name: "NAME", 
        keyPath: \eSURFACE_OF_REVOLUTION.NAME, 
        kind: .explicit, source: .superEntity, mayYieldEntityReference: false)
      entityDef.addAttribute(name: "DIM", 
        keyPath: \eSURFACE_OF_REVOLUTION.DIM, 
        kind: .derived, source: .superEntity, mayYieldEntityReference: false)

      return entityDef.freeze()
    }



//MARK: - Partial Entity

/** Partial Entity
- EXPRESS source code:
```express

    ENTITY surface_of_revolution
      SUBTYPE OF ( swept_surface );
        axis_position  : axis1_placement;
      DERIVE
        axis_line  : line := representation_item( '' ) || geometric_representation_item(  ) || curve(  ) || 
                       line( axis_position.location, representation_item( '' ) || 
                       geometric_representation_item(  ) || vector( axis_position.z, 1 ) );
    END_ENTITY; -- surface_of_revolution (line:31375 file:ap242ed2_mim_lf_v1.101_TY.exp)

```
- ENTITY reference:
	+	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eSURFACE_OF_REVOLUTION``
*/
    public final class PartialEntity : SDAI.PartialEntity, @unchecked Sendable {
      public override class var entityReferenceType: SDAI.EntityReference.Type {
        eSURFACE_OF_REVOLUTION.self
      }

      //ATTRIBUTES
      /// EXPLICIT ATTRIBUTE 
      @_documentation(visibility:public)
      public internal(set) var _axis_position: eAXIS1_PLACEMENT.PRef // PLAIN EXPLICIT ATTRIBUTE

      /// DERIVE ATTRIBUTE
      @_documentation(visibility:public)
      internal func _axis_line__getter(SELF: eSURFACE_OF_REVOLUTION.PRef) -> eLINE.PRef?  {

        let _TEMP1 /* eREPRESENTATION_ITEM.PartialEntity */ = eREPRESENTATION_ITEM.PartialEntity( 
            NAME: SDAI.UNWRAP(tLABEL("")) )
        let _TEMP2 /* eGEOMETRIC_REPRESENTATION_ITEM.PartialEntity */ = 
            eGEOMETRIC_REPRESENTATION_ITEM.PartialEntity(  )
        let _TEMP3 /* SDAI.GENERIC_ENTITY */ = _TEMP1 .||. _TEMP2
        let _TEMP4 /* eCURVE.PartialEntity */ = eCURVE.PartialEntity(  )
        let _TEMP5 /* SDAI.GENERIC_ENTITY */ = _TEMP3 .||. _TEMP4
        let _TEMP6 /* eCARTESIAN_POINT.PRef? */ = SELF.AXIS_POSITION?.LOCATION
        let _TEMP7 /* eREPRESENTATION_ITEM.PartialEntity */ = eREPRESENTATION_ITEM.PartialEntity( 
            NAME: SDAI.UNWRAP(tLABEL("")) )
        let _TEMP8 /* eGEOMETRIC_REPRESENTATION_ITEM.PartialEntity */ = 
            eGEOMETRIC_REPRESENTATION_ITEM.PartialEntity(  )
        let _TEMP9 /* SDAI.GENERIC_ENTITY */ = _TEMP7 .||. _TEMP8
        let _TEMP10 /* eDIRECTION.PRef? */ = SELF.AXIS_POSITION?.Z
        let _TEMP11 /* eVECTOR.PartialEntity */ = eVECTOR.PartialEntity( 
            ORIENTATION: SDAI.UNWRAP(_TEMP10), 
            MAGNITUDE: SDAI.UNWRAP(tLENGTH_MEASURE(1.0000000000e+00)) )
        let _TEMP12 /* SDAI.GENERIC_ENTITY */ = _TEMP9 .||. _TEMP11
        let _TEMP13 /* eLINE.PartialEntity */ = eLINE.PartialEntity( 
            PNT: SDAI.UNWRAP(_TEMP6), 
            DIR: SDAI.UNWRAP(eVECTOR.PRef(/*SDAI.GENERIC_ENTITY*/_TEMP12)) )
        let _TEMP14 /* SDAI.GENERIC_ENTITY */ = _TEMP5 .||. _TEMP13
        return eLINE.PRef(/*SDAI.GENERIC_ENTITY*/_TEMP14)
      }

      public override var typeMembers: Set<SDAI.STRING> {
        var members = Set<SDAI.STRING>()
        members.insert(SDAI.STRING(Self.typeName))
        //SELECT data types (indirectly) referencing the current type as a member of the select list
        members.insert(SDAI.STRING(sAXIAL_GEOMETRY_CONSTRAINT_ELEMENT.typeName)) // -> Self
        return members
      }


      //VALUE COMPARISON SUPPORT
      public override func hashAsValue(into hasher: inout Hasher, visited complexEntities: inout Set<SDAI.ComplexEntity>) {
        super.hashAsValue(into: &hasher, visited: &complexEntities)
        self._axis_position.value.hashAsValue(into: &hasher, visited: &complexEntities)
      }

      public override func isValueEqual(to rhs: SDAI.PartialEntity, visited comppairs: inout Set<SDAI.ComplexPair>) -> Bool {
        guard let rhs = rhs as? Self else { return false }
        if !super.isValueEqual(to: rhs, visited: &comppairs) { return false }
        if let comp = self._axis_position.value.isValueEqualOptionally(to: rhs._axis_position.value, visited: &comppairs)	{
          if !comp { return false }
        }
        else { return false }
        return true
      }

      public override func isValueEqualOptionally(to rhs: SDAI.PartialEntity, visited comppairs: inout Set<SDAI.ComplexPair>) -> Bool? {
        guard let rhs = rhs as? Self else { return false }
        var result: Bool? = true
        if let comp = super.isValueEqualOptionally(to: rhs, visited: &comppairs) {
          if !comp { return false }
        }
        else { result = nil }
        if let comp = self._axis_position.value.isValueEqualOptionally(to: rhs._axis_position.value, visited: &comppairs) {
          if !comp { return false }
        }
        else { result = nil }
        return result
      }


      //EXPRESS IMPLICIT PARTIAL ENTITY CONSTRUCTOR
      /// initialize from explicit attribute values
      public init(AXIS_POSITION: eAXIS1_PLACEMENT.PRef) {

        self._axis_position = AXIS_POSITION

        super.init(asAbstractSuperclass:())
      }

      //PARTIAL ENTITY COPY CONSTRUCTOR
      /// copy constructor
      public required convenience init(from original:SDAI.PartialEntity) {
        let original = original as! Self
        self.init( AXIS_POSITION: original._axis_position )
      }

      //p21 PARTIAL ENTITY CONSTRUCTOR
      /// initialize from ISO 10303-21 exchange structure parameters
      public required convenience init?(
        parameters: [P21Decode.ExchangeStructure.Parameter],
        exchangeStructure: P21Decode.ExchangeStructure
      ) {
        let numParams = 1
        guard parameters.count == numParams
        else { exchangeStructure.error = "number of p21 parameters(\(parameters.count)) are different from expected(\(numParams)) for partial entity(\(Self.entityName)) constructor"; return nil }

        guard case .success(let p0) = exchangeStructure.recoverRequiredParameter(as: eAXIS1_PLACEMENT.PRef.self, from: parameters[0])
        else { exchangeStructure.add(errorContext: "while recovering parameter [0]AXIS_POSITION for partial entity(\(Self.entityName)) constructor"); return nil }

        self.init( AXIS_POSITION: p0 )
      }
    }
  }
}
