/* file: swept_disk_solid.swift 	 generated: Sat Aug 14 13:46:02 2021 */

/* This file was generated by the EXPRESS to Swift translator "exp2swift", 
    derived from STEPcode (formerly NIST's SCL).
 exp2swift version: v.1.0.0, derived from stepcode v0.8 as of 2019/11/23 
 WARNING: You probably don't want to edit it since your modifications 
    will be lost if exp2swift is used to regenerate it.
 */

 
import SwiftSDAIcore

extension AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF {
//MARK: -ENTITY DEFINITION in EXPRESS
/*

  ENTITY swept_disk_solid
    SUBTYPE OF ( solid_model );
      directrix     : curve;
      radius        : positive_length_measure;
      inner_radius  : OPTIONAL positive_length_measure;
      start_param   : REAL;
      end_param     : REAL;
    WHERE
      wr1: ( directrix.dim = 3 );
      wr2: ( ( NOT EXISTS( inner_radius ) ) OR ( radius > inner_radius ) );
  END_ENTITY; -- swept_disk_solid (line:31442 file:ap242ed2_mim_lf_v1.101.TY.exp)

*/


//MARK: - ALL DEFINED ATTRIBUTES
/*
  SUPER- ENTITY(1)	representation_item
    ATTR:  name,	TYPE: label -- EXPLICIT


  SUPER- ENTITY(2)	geometric_representation_item
    ATTR:  dim,	TYPE: dimension_count -- DERIVED
      := dimension_of( SELF )


  SUPER- ENTITY(3)	solid_model
    (no local attributes)

  ENTITY(SELF)	swept_disk_solid
    ATTR:  directrix,	TYPE: curve -- EXPLICIT

    ATTR:  radius,	TYPE: positive_length_measure -- EXPLICIT

    ATTR:  inner_radius,	TYPE: OPTIONAL positive_length_measure -- EXPLICIT

    ATTR:  start_param,	TYPE: REAL -- EXPLICIT

    ATTR:  end_param,	TYPE: REAL -- EXPLICIT


*/


//MARK: - Partial Entity
  public final class _swept_disk_solid : SDAI.PartialEntity {
    public override class var entityReferenceType: SDAI.EntityReference.Type {
      eSWEPT_DISK_SOLID.self
    }

    //ATTRIBUTES
    /// EXPLICIT ATTRIBUTE 
    public internal(set) var _directrix: eCURVE // PLAIN EXPLICIT ATTRIBUTE

    /// EXPLICIT ATTRIBUTE 
    public internal(set) var _radius: tPOSITIVE_LENGTH_MEASURE // PLAIN EXPLICIT ATTRIBUTE

    /// EXPLICIT ATTRIBUTE 
    public internal(set) var _inner_radius: tPOSITIVE_LENGTH_MEASURE?  // PLAIN EXPLICIT ATTRIBUTE

    /// EXPLICIT ATTRIBUTE 
    public internal(set) var _start_param: SDAI.REAL // PLAIN EXPLICIT ATTRIBUTE

    /// EXPLICIT ATTRIBUTE 
    public internal(set) var _end_param: SDAI.REAL // PLAIN EXPLICIT ATTRIBUTE

    public override var typeMembers: Set<SDAI.STRING> {
      var members = Set<SDAI.STRING>()
      members.insert(SDAI.STRING(Self.typeName))
      return members
    }


    //VALUE COMPARISON SUPPORT
    public override func hashAsValue(into hasher: inout Hasher, visited complexEntities: inout Set<SDAI.ComplexEntity>) {
      super.hashAsValue(into: &hasher, visited: &complexEntities)
      self._directrix.value.hashAsValue(into: &hasher, visited: &complexEntities)
      self._radius.value.hashAsValue(into: &hasher, visited: &complexEntities)
      self._inner_radius?.value.hashAsValue(into: &hasher, visited: &complexEntities)
      self._start_param.value.hashAsValue(into: &hasher, visited: &complexEntities)
      self._end_param.value.hashAsValue(into: &hasher, visited: &complexEntities)
    }

    public override func isValueEqual(to rhs: SDAI.PartialEntity, visited comppairs: inout Set<SDAI.ComplexPair>) -> Bool {
      guard let rhs = rhs as? Self else { return false }
      if !super.isValueEqual(to: rhs, visited: &comppairs) { return false }
      if let comp = self._directrix.value.isValueEqualOptionally(to: rhs._directrix.value, visited: &comppairs)	{
        if !comp { return false }
      }
      else { return false }
      if let comp = self._radius.value.isValueEqualOptionally(to: rhs._radius.value, visited: &comppairs)	{
        if !comp { return false }
      }
      else { return false }
      if let comp = self._inner_radius?.value.isValueEqualOptionally(to: rhs._inner_radius?.value, visited: &comppairs)	{
        if !comp { return false }
      }
      else { return false }
      if let comp = self._start_param.value.isValueEqualOptionally(to: rhs._start_param.value, visited: &comppairs)	{
        if !comp { return false }
      }
      else { return false }
      if let comp = self._end_param.value.isValueEqualOptionally(to: rhs._end_param.value, visited: &comppairs)	{
        if !comp { return false }
      }
      else { return false }
      return true
    }

    public override func isValueEqualOptionally(to rhs: SDAI.PartialEntity, visited comppairs: inout Set<SDAI.ComplexPair>) -> Bool? {
      guard let rhs = rhs as? Self else { return false }
      var result: Bool? = true
      if let comp = super.isValueEqualOptionally(to: rhs, visited: &comppairs) {
        if !comp { return false }
      }
      else { result = nil }
      if let comp = self._directrix.value.isValueEqualOptionally(to: rhs._directrix.value, visited: &comppairs) {
        if !comp { return false }
      }
      else { result = nil }
      if let comp = self._radius.value.isValueEqualOptionally(to: rhs._radius.value, visited: &comppairs) {
        if !comp { return false }
      }
      else { result = nil }
      if let comp = self._inner_radius?.value.isValueEqualOptionally(to: rhs._inner_radius?.value, visited: &comppairs) {
        if !comp { return false }
      }
      else { result = nil }
      if let comp = self._start_param.value.isValueEqualOptionally(to: rhs._start_param.value, visited: &comppairs) {
        if !comp { return false }
      }
      else { result = nil }
      if let comp = self._end_param.value.isValueEqualOptionally(to: rhs._end_param.value, visited: &comppairs) {
        if !comp { return false }
      }
      else { result = nil }
      return result
    }


    //MARK: WHERE RULES (ENTITY)
    public static func WHERE_wr1(SELF: eSWEPT_DISK_SOLID?) -> SDAI.LOGICAL {
      guard let SELF = SELF else { return SDAI.UNKNOWN }

      let _TEMP1 = SELF.DIRECTRIX.DIM
      let _TEMP2 = _TEMP1 .==. SDAI.FORCE_OPTIONAL(SDAI.INTEGER(3))
      return _TEMP2
    }
    public static func WHERE_wr2(SELF: eSWEPT_DISK_SOLID?) -> SDAI.LOGICAL {
      guard let SELF = SELF else { return SDAI.UNKNOWN }

      let _TEMP1 = SDAI.EXISTS(SELF.INNER_RADIUS)
      let _TEMP2 =  !_TEMP1
      let _TEMP3 = SDAI.FORCE_OPTIONAL(SELF.RADIUS) > SELF.INNER_RADIUS
      let _TEMP4 = _TEMP2 || _TEMP3
      return _TEMP4
    }

    //EXPRESS IMPLICIT PARTIAL ENTITY CONSTRUCTOR
    public init(DIRECTRIX: eCURVE, RADIUS: tPOSITIVE_LENGTH_MEASURE, INNER_RADIUS: tPOSITIVE_LENGTH_MEASURE? , 
                START_PARAM: SDAI.REAL, END_PARAM: SDAI.REAL) {
      self._directrix = DIRECTRIX
      self._radius = RADIUS
      self._inner_radius = INNER_RADIUS
      self._start_param = START_PARAM
      self._end_param = END_PARAM
      super.init(asAbstructSuperclass:())

    }

    //p21 PARTIAL ENTITY CONSTRUCTOR
    public required convenience init?(parameters: [P21Decode.ExchangeStructure.Parameter], exchangeStructure: P21Decode.ExchangeStructure) {
      let numParams = 5
      guard parameters.count == numParams
      else { exchangeStructure.error = "number of p21 parameters(\(parameters.count)) are different from expected(\(numParams)) for entity(\(Self.entityName)) constructor"; return nil }

      guard case .success(let p0) = exchangeStructure.recoverRequiredParameter(as: eCURVE.self, from: parameters[0])
      else { exchangeStructure.add(errorContext: "while recovering parameter #0 for entity(\(Self.entityName)) constructor"); return nil }

      guard case .success(let p1) = exchangeStructure.recoverRequiredParameter(as: tPOSITIVE_LENGTH_MEASURE.self, from: parameters[1])
      else { exchangeStructure.add(errorContext: "while recovering parameter #1 for entity(\(Self.entityName)) constructor"); return nil }

      guard case .success(let p2) = exchangeStructure.recoverOptionalParameter(as: tPOSITIVE_LENGTH_MEASURE.self, from: parameters[2])
      else { exchangeStructure.add(errorContext: "while recovering parameter #2 for entity(\(Self.entityName)) constructor"); return nil }

      guard case .success(let p3) = exchangeStructure.recoverRequiredParameter(as: SDAI.REAL.self, from: parameters[3])
      else { exchangeStructure.add(errorContext: "while recovering parameter #3 for entity(\(Self.entityName)) constructor"); return nil }

      guard case .success(let p4) = exchangeStructure.recoverRequiredParameter(as: SDAI.REAL.self, from: parameters[4])
      else { exchangeStructure.add(errorContext: "while recovering parameter #4 for entity(\(Self.entityName)) constructor"); return nil }

      self.init( DIRECTRIX: p0, RADIUS: p1, INNER_RADIUS: p2, START_PARAM: p3, END_PARAM: p4 )
    }
  }


//MARK: - Entity Reference

/** ENTITY reference
- EXPRESS:
```express
  ENTITY swept_disk_solid
    SUBTYPE OF ( solid_model );
      directrix     : curve;
      radius        : positive_length_measure;
      inner_radius  : OPTIONAL positive_length_measure;
      start_param   : REAL;
      end_param     : REAL;
    WHERE
      wr1: ( directrix.dim = 3 );
      wr2: ( ( NOT EXISTS( inner_radius ) ) OR ( radius > inner_radius ) );
  END_ENTITY; -- swept_disk_solid (line:31442 file:ap242ed2_mim_lf_v1.101.TY.exp)

```
*/
  public final class eSWEPT_DISK_SOLID : SDAI.EntityReference {

    //MARK: PARTIAL ENTITY
    public override class var partialEntityType: SDAI.PartialEntity.Type {
      _swept_disk_solid.self
    }
    public let partialEntity: _swept_disk_solid

    //MARK: SUPERTYPES
    public let super_eREPRESENTATION_ITEM: eREPRESENTATION_ITEM 	// [1]
    public let super_eGEOMETRIC_REPRESENTATION_ITEM: eGEOMETRIC_REPRESENTATION_ITEM 	// [2]
    public let super_eSOLID_MODEL: eSOLID_MODEL 	// [3]
    public var super_eSWEPT_DISK_SOLID: eSWEPT_DISK_SOLID { return self } 	// [4]

    //MARK: SUBTYPES

    //MARK: ATTRIBUTES
    /// __EXPLICIT__ attribute
    /// - origin: SELF( ``eSWEPT_DISK_SOLID`` )
    public var INNER_RADIUS: tPOSITIVE_LENGTH_MEASURE?  {
      get {
        return self.partialEntity._inner_radius
      }
      set(newValue) {
        let partial = self.partialEntity
        partial._inner_radius = newValue
      }
    }

    /// __EXPLICIT__ attribute
    /// - origin: SELF( ``eSWEPT_DISK_SOLID`` )
    public var END_PARAM: SDAI.REAL {
      get {
        return SDAI.UNWRAP( self.partialEntity._end_param )
      }
      set(newValue) {
        let partial = self.partialEntity
        partial._end_param = SDAI.UNWRAP(newValue)
      }
    }

    /// __EXPLICIT__ attribute
    /// - origin: SELF( ``eSWEPT_DISK_SOLID`` )
    public var RADIUS: tPOSITIVE_LENGTH_MEASURE {
      get {
        return SDAI.UNWRAP( self.partialEntity._radius )
      }
      set(newValue) {
        let partial = self.partialEntity
        partial._radius = SDAI.UNWRAP(newValue)
      }
    }

    /// __EXPLICIT__ attribute
    /// - origin: SELF( ``eSWEPT_DISK_SOLID`` )
    public var DIRECTRIX: eCURVE {
      get {
        return SDAI.UNWRAP( self.partialEntity._directrix )
      }
      set(newValue) {
        let partial = self.partialEntity
        partial._directrix = SDAI.UNWRAP(newValue)
      }
    }

    /// __EXPLICIT__ attribute
    /// - origin: SELF( ``eSWEPT_DISK_SOLID`` )
    public var START_PARAM: SDAI.REAL {
      get {
        return SDAI.UNWRAP( self.partialEntity._start_param )
      }
      set(newValue) {
        let partial = self.partialEntity
        partial._start_param = SDAI.UNWRAP(newValue)
      }
    }

    /// __EXPLICIT__ attribute
    /// - origin: SUPER( ``eREPRESENTATION_ITEM`` )
    public var NAME: tLABEL {
      get {
        return SDAI.UNWRAP( super_eREPRESENTATION_ITEM.partialEntity._name )
      }
      set(newValue) {
        let partial = super_eREPRESENTATION_ITEM.partialEntity
        partial._name = SDAI.UNWRAP(newValue)
      }
    }

    /// __DERIVE__ attribute
    /// - origin: SUPER( ``eGEOMETRIC_REPRESENTATION_ITEM`` )
    public var DIM: tDIMENSION_COUNT?  {
      get {
        if let cached = cachedValue(derivedAttributeName:"DIM") {
          return cached.value as! tDIMENSION_COUNT? 
        }
        let origin = super_eGEOMETRIC_REPRESENTATION_ITEM
        let value = tDIMENSION_COUNT(origin.partialEntity._dim__getter(SELF: origin))
        updateCache(derivedAttributeName:"DIM", value:value)
        return value
      }
    }


    //MARK: INITIALIZERS
    public convenience init?(_ entityRef: SDAI.EntityReference?) {
      let complex = entityRef?.complexEntity
      self.init(complex: complex)
    }

    public required init?(complex complexEntity: SDAI.ComplexEntity?) {
      guard let partial = complexEntity?.partialEntityInstance(_swept_disk_solid.self) else { return nil }
      self.partialEntity = partial

      guard let super1 = complexEntity?.entityReference(eREPRESENTATION_ITEM.self) else { return nil }
      self.super_eREPRESENTATION_ITEM = super1

      guard let super2 = complexEntity?.entityReference(eGEOMETRIC_REPRESENTATION_ITEM.self) else { return nil }
      self.super_eGEOMETRIC_REPRESENTATION_ITEM = super2

      guard let super3 = complexEntity?.entityReference(eSOLID_MODEL.self) else { return nil }
      self.super_eSOLID_MODEL = super3

      super.init(complex: complexEntity)
    }

    public required convenience init?<G: SDAIGenericType>(fromGeneric generic: G?) {
      guard let entityRef = generic?.entityReference else { return nil }
      self.init(complex: entityRef.complexEntity)
    }

    public convenience init?<S: SDAISelectType>(_ select: S?) { self.init(possiblyFrom: select) }
    public convenience init?(_ complex: SDAI.ComplexEntity?) { self.init(complex: complex) }


    //MARK: WHERE RULE VALIDATION (ENTITY)
    public override class func validateWhereRules(instance:SDAI.EntityReference?, prefix:SDAI.WhereLabel) -> [SDAI.WhereLabel:SDAI.LOGICAL] {
      guard let instance = instance as? Self else { return [:] }

      let prefix2 = prefix + " \(instance)"

      var result = super.validateWhereRules(instance:instance, prefix:prefix2)
      result[prefix2 + " .WHERE_wr1"] = _swept_disk_solid.WHERE_wr1(SELF: instance)
      result[prefix2 + " .WHERE_wr2"] = _swept_disk_solid.WHERE_wr2(SELF: instance)
      return result
    }


    //MARK: DICTIONARY DEFINITION
    public class override var entityDefinition: SDAIDictionarySchema.EntityDefinition { _entityDefinition }
    private static let _entityDefinition: SDAIDictionarySchema.EntityDefinition = createEntityDefinition()

    private static func createEntityDefinition() -> SDAIDictionarySchema.EntityDefinition {
      let entityDef = SDAIDictionarySchema.EntityDefinition(name: "SWEPT_DISK_SOLID", type: self, explicitAttributeCount: 5)

      //MARK: SUPERTYPE REGISTRATIONS
      entityDef.add(supertype: eREPRESENTATION_ITEM.self)
      entityDef.add(supertype: eGEOMETRIC_REPRESENTATION_ITEM.self)
      entityDef.add(supertype: eSOLID_MODEL.self)
      entityDef.add(supertype: eSWEPT_DISK_SOLID.self)

      //MARK: ATTRIBUTE REGISTRATIONS
      entityDef.addAttribute(name: "INNER_RADIUS", keyPath: \eSWEPT_DISK_SOLID.INNER_RADIUS, 
        kind: .explicitOptional, source: .thisEntity, mayYieldEntityReference: false)
      entityDef.addAttribute(name: "END_PARAM", keyPath: \eSWEPT_DISK_SOLID.END_PARAM, 
        kind: .explicit, source: .thisEntity, mayYieldEntityReference: false)
      entityDef.addAttribute(name: "RADIUS", keyPath: \eSWEPT_DISK_SOLID.RADIUS, 
        kind: .explicit, source: .thisEntity, mayYieldEntityReference: false)
      entityDef.addAttribute(name: "DIRECTRIX", keyPath: \eSWEPT_DISK_SOLID.DIRECTRIX, 
        kind: .explicit, source: .thisEntity, mayYieldEntityReference: true)
      entityDef.addAttribute(name: "START_PARAM", keyPath: \eSWEPT_DISK_SOLID.START_PARAM, 
        kind: .explicit, source: .thisEntity, mayYieldEntityReference: false)
      entityDef.addAttribute(name: "NAME", keyPath: \eSWEPT_DISK_SOLID.NAME, 
        kind: .explicit, source: .superEntity, mayYieldEntityReference: false)
      entityDef.addAttribute(name: "DIM", keyPath: \eSWEPT_DISK_SOLID.DIM, 
        kind: .derived, source: .superEntity, mayYieldEntityReference: false)

      return entityDef
    }

  }
}
